### PR TITLE
 Fix cyclic reference introduced in Log.cpp

### PR DESCRIPTION
**Pull request by Bia10**
Add few helperFunctions
Add validity checks to macro execution
Change GUI a bit

### CODE REVIEW

**Comment by jnpl95** [comment]
I reverted to the commit before I merged this because the UI was messed up. I'm going to fix the UI today evening and add in the changes that you made.

**Comment by jnpl95** [comment]
GUI overhaul might take some time, feel free to work on your branch and send pull requests. I need some time to fix up the GUI so I'll incorporate your changes manually.

**Comment by Bia10** [comment]
How exactly Messed up?

**Comment by jnpl95** [comment]
I was working on the GUI (a few changes) and I didn't realize that merging your commits would cause a conflict. Don't worry about it, I'll just incorporate your changes once I finish it.

**Comment by Bia10** [comment]
Wait please ill throw in another request with more GUI change i like it for now :D, Please stop bloating the GUI with retarded panels, group hacks in groupboxes the panels generate tonshit of pointless code from mine perspective.

**Comment by Bia10** [comment]
BTW please could you take a look at AutoBuff? it seems to be entirely buggy. IDK why haven't checked at all.

Going to sleep now, did a bit of reversing research found useful references :]

**Comment by jnpl95** [comment]
Sorry man, I just prefer designing the GUI. The group boxes/panels help keep the hacks organized in my opinion, but I agree there are too many panels in the background. I will delete some of them to make it easier to move things around in the GUI. 

I like most of your changes, altho there are some I don't like (for example, I don't think the hp/mp/exp bars look good...the numbers are sufficient). So I will work on the GUI tonight and hopefully commit my changes before tomorrow. If you don't like my GUI changes that I am going to make, feel free to continue on your branch. I'll just update the other changes. 

I will look into autobuff. Could you tell me what server you're testing on? So that I can get the same results and hopefully fix the issues that come up

Anyways, thanks so much for your commits, I appreciate your help in making this trainer better. Sorry if I'm a slow coder, I'll try to work more on a day by day basis rather than a commit every week or so.

**Pull request merged**
